[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "armalint"
version = "0.1.0"
description = "Arma 3 SQF linter"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
armalint = "armalint.__main__:_main"
armalint-update = "armalint.update:main"
armalint-update-commands = "armalint.update_commands:main"

[tool.setuptools.packages.find]
include = ["armalint*"]

[tool.setuptools.package-data]
armalint = ["data/commands.txt"]
