"""Parser for Arma 3's rapified (binarized) ``config.bin`` format.

Arma 3 stores compiled configs in a binary form ("raP" after the four-byte
signature). This module reads that form back into a plain tree of
:class:`ConfigClass` nodes so that callers can navigate class names and read
string/scalar/array properties (which is all ``CfgFunctions`` extraction
needs). Only the standard library is used.

The format implemented here is the *Arma* variant (not the older OFP layout).
It was pinned down by porting, byte-for-byte, the two independent open-source
implementations listed below and then validating against real Bohemia-rapified
fixtures (see the ``__main__`` self-test, which embeds golden ``.bi.bin``
files generated by Bohemia's own rapifier):

References
----------
* `WoozyMasta/rap` (Go RAP codec; well-documented token table and decoder)
  https://github.com/woozymasta/rap
  - ``binary_primitives.go`` (compressed int, cstring, little-endian reads)
  - ``codec_decode.go`` (entry/subtype dispatch)
* `BrettMayson/HEMTT` (Rust; the de-facto Arma 3 build tool)
  https://github.com/BrettMayson/HEMTT
  - ``libs/config/src/rapify/*.rs`` (``class.rs``, ``property.rs``,
    ``array.rs``, ``number.rs``, ``str.rs``, ``config.rs``)
  - ``libs/common/src/io.rs`` (``read_cstring`` / ``read_compressed_int``)
* `KoffeinFlummi/armake` (Rust; the ancestor of HEMTT's io.rs) — consulted
  indirectly via HEMTT's io.rs attribution.

Format summary
--------------
A rapified file is::

    header (16 bytes)
        b"\\0raP"                     magic (00 72 61 50)
        u32 always0                   == 0
        u32 always8                   == 8
        u32 enum_offset               absolute offset of the enum table
    root class body (at offset 16)

A *class body* is::

    cstring base                      parent class name (empty for root)
    compressed_int entry_count
    entry_count entries
    u32 next_class_offset             (ignored here; child bodies are found
                                       via the explicit offsets below)

Each *entry* starts with a one-byte type code:

    ====  ==============================================================
    code   meaning / payload
    ====  ==============================================================
    0      class:        cstring name + u32 offset to that class's body
    1      scalar entry: u8 subtype + cstring name + scalar payload
    2      array entry:  cstring name + array payload
    3      extern class: cstring name only (forward declaration, no body)
    4      delete:       cstring name only (``delete Name;``)
    5      array append: u32 flags (0/1) + cstring name + array payload
    ====  ==============================================================

*Scalar* and *array-element* subtypes (one byte):

    ====  ==============================================
    code   meaning / payload
    ====  ==============================================
    0      string:    cstring
    1      float:     f32 (4 bytes)
    2      int32:     i32 (4 bytes)
    3      (array elements only) nested array
    4      __EVAL expression: cstring (stored as a plain string here)
    6      int64:     i64 (8 bytes)
    ====  ==============================================

An *array payload* is a ``compressed_int`` element count followed by that many
elements, each a subtype byte plus payload (subtype 3 recurses as a nested
array). All integers are little-endian. ``delete`` and ``extern`` entries are
dropped (they carry no class body); unknown entry/subtype codes abort the
containing class body conservatively rather than raising.

Serialization
-------------
:func:`rapify` inverts :func:`parse_config_bin`, serializing a
:class:`ConfigClass` tree back into rapified bytes (ported from
``WoozyMasta/rap`` ``codec_encode.go``). Because ``ConfigClass`` does not
retain the inherited parent name nor ``extern``/``delete`` entries, every class
is emitted with an empty base and the root's enum table is empty; scalars are
encoded by Python type (``str``/``int``/``float`` -> string / int32-or-int64 /
float32). For any tree built from these node types,
``parse_config_bin(rapify(config))`` round-trips.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field

#: File signature: b"\\0raP".
MAGIC = b"\x00raP"

#: Size of the fixed header (magic + always0 + always8 + enum offset).
_HEADER_SIZE = 16

# Entry type codes (the first byte of each entry inside a class body).
ENTRY_CLASS = 0
ENTRY_SCALAR = 1
ENTRY_ARRAY = 2
ENTRY_EXTERN = 3
ENTRY_DELETE = 4
ENTRY_ARRAY_APPEND = 5

# Scalar / array-element subtype codes.
SUBTYPE_STRING = 0
SUBTYPE_FLOAT = 1
SUBTYPE_INT32 = 2
SUBTYPE_ARRAY = 3  # array-element context only: a nested array
SUBTYPE_EXPR = 4  # __EVAL expression (stored as its source text)
SUBTYPE_INT64 = 6


class _FormatError(Exception):
    """Raised internally when the byte stream is truncated or malformed.

    The public parser never lets this escape: it is converted into a
    conservative, partial parse of the surrounding class body.
    """


@dataclass
class ConfigClass:
    """A node in a parsed rapified config tree.

    ``properties`` maps a property name to its value, which is one of:

    * ``str``      — a string value (and also ``__EVAL`` expression text)
    * ``int``      — an int32/int64 value
    * ``float``    — a float value
    * ``list``     — an array value (may nest arbitrarily)

    ``children`` holds nested classes in file order. The inherited parent
    class name is deliberately not retained (it is not needed to navigate the
    tree or to read properties).
    """

    name: str
    properties: dict = field(default_factory=dict)
    children: list = field(default_factory=list)


class _Reader:
    """Bounds-checked little-endian reader over a ``bytes`` buffer."""

    __slots__ = ("data", "pos")

    def __init__(self, data: bytes) -> None:
        self.data = data
        self.pos = 0

    def read_bytes(self, n: int) -> bytes:
        if n < 0 or self.pos + n > len(self.data):
            raise _FormatError("truncated rapified stream")
        b = self.data[self.pos:self.pos + n]
        self.pos += n
        return b

    def read_byte(self) -> int:
        return self.read_bytes(1)[0]

    def read_u32(self) -> int:
        return struct.unpack("<I", self.read_bytes(4))[0]

    def read_i32(self) -> int:
        return struct.unpack("<i", self.read_bytes(4))[0]

    def read_i64(self) -> int:
        return struct.unpack("<q", self.read_bytes(8))[0]

    def read_f32(self) -> float:
        return struct.unpack("<f", self.read_bytes(4))[0]

    def read_cstring(self) -> str:
        end = self.data.find(b"\x00", self.pos)
        if end < 0:
            raise _FormatError("unterminated string")
        raw = self.data[self.pos:end]
        self.pos = end + 1
        return _decode(raw)

    def read_compressed_int(self) -> int:
        """Read a Bohemia "compressed" integer (7 bits per byte, big-endian groups)."""
        result = 0
        for i in range(5):  # a u32 needs at most 5 bytes
            b = self.read_byte()
            result |= (b & 0x7F) << (7 * i)
            if b < 0x80:
                return result
        raise _FormatError("compressed integer too long")


def _decode(raw: bytes) -> str:
    """Decode a name/string, preferring UTF-8 and falling back to latin-1."""
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw.decode("latin-1")


def _read_scalar(r: _Reader, subtype: int):
    """Read a scalar value by subtype code. Raises ``_FormatError`` on unknown codes."""
    if subtype == SUBTYPE_STRING:
        return r.read_cstring()
    if subtype == SUBTYPE_FLOAT:
        return r.read_f32()
    if subtype == SUBTYPE_INT32:
        return r.read_i32()
    if subtype == SUBTYPE_EXPR:
        return r.read_cstring()  # __EVAL expression text
    if subtype == SUBTYPE_INT64:
        return r.read_i64()
    raise _FormatError(f"unknown scalar subtype {subtype}")


def _read_array(r: _Reader) -> list:
    """Read an array payload (compressed count followed by typed elements)."""
    count = r.read_compressed_int()
    items: list = []
    for _ in range(count):
        subtype = r.read_byte()
        if subtype == SUBTYPE_ARRAY:
            items.append(_read_array(r))
        elif subtype in (SUBTYPE_STRING, SUBTYPE_FLOAT, SUBTYPE_INT32, SUBTYPE_EXPR, SUBTYPE_INT64):
            items.append(_read_scalar(r, subtype))
        else:
            raise _FormatError(f"unknown array element subtype {subtype}")
    return items


def _parse_class_at(data: bytes, offset: int, name: str) -> ConfigClass:
    """Parse the class body at absolute ``offset`` and return a ``ConfigClass``.

    Any malformed or unknown token aborts the *rest of this class body* (the
    entries already read are kept), so malformed input degrades to a partial
    tree instead of raising.
    """
    cls = ConfigClass(name=name)
    r = _Reader(data)
    r.pos = offset

    try:
        _base = r.read_cstring()  # inherited parent name (not retained)
        count = r.read_compressed_int()
    except _FormatError:
        return cls

    for _ in range(count):
        try:
            code = r.read_byte()
        except _FormatError:
            break

        if code == ENTRY_CLASS:
            try:
                child_name = r.read_cstring()
                child_offset = r.read_u32()
            except _FormatError:
                break
            if 0 <= child_offset < len(data):
                cls.children.append(_parse_class_at(data, child_offset, child_name))

        elif code == ENTRY_SCALAR:
            try:
                subtype = r.read_byte()
                prop_name = r.read_cstring()
            except _FormatError:
                break
            try:
                cls.properties[prop_name] = _read_scalar(r, subtype)
            except _FormatError:
                break

        elif code == ENTRY_ARRAY:
            try:
                prop_name = r.read_cstring()
            except _FormatError:
                break
            try:
                cls.properties[prop_name] = _read_array(r)
            except _FormatError:
                break

        elif code == ENTRY_ARRAY_APPEND:
            # flags u32 (append bit) + name + array; the append flag is not
            # needed for name extraction, so the value is stored like a plain
            # array assignment.
            try:
                _flags = r.read_u32()
                prop_name = r.read_cstring()
            except _FormatError:
                break
            try:
                cls.properties[prop_name] = _read_array(r)
            except _FormatError:
                break

        elif code in (ENTRY_EXTERN, ENTRY_DELETE):
            # Forward declaration / deletion: name only, no body — skip.
            try:
                r.read_cstring()
            except _FormatError:
                break

        else:
            # Unknown entry type: we cannot know its size, so stop reading this
            # class body rather than risk a desync or a crash.
            break

    return cls


def parse_config_bin(data: bytes) -> ConfigClass:
    """Parse a rapified ``config.bin`` payload and return the root ``ConfigClass``.

    Raises ``ValueError`` if ``data`` is not a rapified Arma config (bad magic
    or an unsupported header version). Once the header is accepted, parsing is
    conservative: truncated or unknown tokens yield a partial tree rather than
    an exception.
    """
    if not isinstance(data, (bytes, bytearray)):
        raise TypeError("parse_config_bin() expects bytes")
    data = bytes(data)

    if len(data) < _HEADER_SIZE or data[:4] != MAGIC:
        raise ValueError("not a rapified config.bin (bad magic)")

    _always0 = struct.unpack_from("<I", data, 4)[0]
    always8 = struct.unpack_from("<I", data, 8)[0]
    _enum_offset = struct.unpack_from("<I", data, 12)[0]

    # ``always8`` discriminates the Arma layout from the older OFP layout; the
    # latter is out of scope here.
    if always8 != 8:
        raise ValueError(f"unsupported rapified config variant (header version {always8})")

    return _parse_class_at(data, _HEADER_SIZE, "")


def _encode_cstring(value: str) -> bytes:
    return value.encode("utf-8") + b"\x00"


def _encode_compressed_int(value: int) -> bytes:
    """Encode a non-negative integer as a Bohemia compressed int (7-bit groups, LSB-first)."""
    if value < 0:
        raise ValueError(f"cannot encode negative compressed int {value}")
    out = bytearray()
    while value > 0x7F:
        out.append(0x80 | (value & 0x7F))
        value >>= 7
    out.append(value)
    return bytes(out)


def _encode_scalar(value) -> tuple[int, bytes]:
    """Encode a Python scalar to ``(subtype, payload_bytes)``.

    ``str`` -> string (0), ``bool`` -> int32 (2), ``int`` -> int32 (2) when it
    fits in 32 bits otherwise int64 (6), ``float`` -> float32 (1). Raises
    ``TypeError`` for anything else.
    """
    if isinstance(value, bool):
        return SUBTYPE_INT32, struct.pack("<i", 1 if value else 0)
    if isinstance(value, str):
        return SUBTYPE_STRING, _encode_cstring(value)
    if isinstance(value, int):
        if -(1 << 31) <= value <= (1 << 31) - 1:
            return SUBTYPE_INT32, struct.pack("<i", value)
        return SUBTYPE_INT64, struct.pack("<q", value)
    if isinstance(value, float):
        return SUBTYPE_FLOAT, struct.pack("<f", value)
    raise TypeError(f"unsupported config value {value!r}")


def _encode_array(arr: list) -> bytes:
    """Encode an array payload (compressed count, then typed elements; lists recurse)."""
    out = bytearray(_encode_compressed_int(len(arr)))
    for item in arr:
        if isinstance(item, list):
            out.append(SUBTYPE_ARRAY)
            out += _encode_array(item)
        else:
            subtype, payload = _encode_scalar(item)
            out.append(subtype)
            out += payload
    return bytes(out)


def _class_entry_len(name: str) -> int:
    # Entry type byte + name cstring + u32 child-body offset.
    return 1 + len(_encode_cstring(name)) + 4


def _property_entry_len(name: str, value) -> int:
    if isinstance(value, list):
        return 1 + len(_encode_cstring(name)) + len(_encode_array(value))
    _subtype, payload = _encode_scalar(value)
    return 1 + 1 + len(_encode_cstring(name)) + len(payload)


def _class_body_size(cls: ConfigClass) -> int:
    count = len(cls.properties) + len(cls.children)
    size = len(_encode_cstring("")) + len(_encode_compressed_int(count))
    for name, value in cls.properties.items():
        size += _property_entry_len(name, value)
    for child in cls.children:
        size += _class_entry_len(child.name)
    size += 4  # trailing next-class offset
    for child in cls.children:
        size += _class_body_size(child)
    return size


def rapify(config: ConfigClass) -> bytes:
    """Serialize ``config`` back into rapified ``config.bin`` bytes.

    This is the inverse of :func:`parse_config_bin` and satisfies
    ``parse_config_bin(rapify(c))`` for trees of :class:`ConfigClass` nodes.
    The layout follows the reference encoder (``WoozyMasta/rap``
    ``codec_encode.go``): a 16-byte header, class bodies carrying a base name,
    an entry count, entries, and a trailing next-class offset, plus an empty
    enum table. Because ``ConfigClass`` drops the inherited parent name and
    ``extern``/``delete`` entries, those never appear in the output.
    """
    if not isinstance(config, ConfigClass):
        raise TypeError("rapify() expects a ConfigClass")

    offsets: dict[int, int] = {}

    def assign(cls: ConfigClass, off: int) -> None:
        offsets[id(cls)] = off
        count = len(cls.properties) + len(cls.children)
        head = len(_encode_cstring("")) + len(_encode_compressed_int(count))
        head += sum(_property_entry_len(n, v) for n, v in cls.properties.items())
        head += sum(_class_entry_len(c.name) for c in cls.children)
        head += 4  # trailing next-class offset
        child_off = off + head
        for child in cls.children:
            assign(child, child_off)
            child_off += _class_body_size(child)

    assign(config, _HEADER_SIZE)

    def emit(cls: ConfigClass) -> bytes:
        out = bytearray()
        count = len(cls.properties) + len(cls.children)
        out += _encode_cstring("")
        out += _encode_compressed_int(count)
        for name, value in cls.properties.items():
            if isinstance(value, list):
                out.append(ENTRY_ARRAY)
                out += _encode_cstring(name)
                out += _encode_array(value)
            else:
                subtype, payload = _encode_scalar(value)
                out.append(ENTRY_SCALAR)
                out.append(subtype)
                out += _encode_cstring(name)
                out += payload
        for child in cls.children:
            out.append(ENTRY_CLASS)
            out += _encode_cstring(child.name)
            out += struct.pack("<I", offsets[id(child)])
        end = offsets[id(cls)] + _class_body_size(cls)
        out += struct.pack("<I", end)
        for child in cls.children:
            out += emit(child)
        return bytes(out)

    body = emit(config)
    enum_offset = _HEADER_SIZE + len(body)
    return (
        MAGIC
        + struct.pack("<I", 0)
        + struct.pack("<I", 8)
        + struct.pack("<I", enum_offset)
        + body
        + struct.pack("<I", 0)  # empty enum table
    )


if __name__ == "__main__":
    # ---------------------------------------------------------------------
    # Self-test. Part 1 validates against real Bohemia-rapified golden files
    # (the ".bi.bin" fixtures from WoozyMasta/rap's byte-parity test, which
    # assert their encoder produces byte-identical output to BI's rapifier).
    # The bytes are embedded as hex so the test is self-contained.
    # ---------------------------------------------------------------------

    def _real(hexstr: str) -> bytes:
        return bytes.fromhex(hexstr)

    # class_chain: class CfgA { class A { x=1; }; class B: A { y=2; };
    #                        class C: B { z=3; }; };
    chain = _real(
        "0072615000000000080000006700000000010043666741002000000067000000"
        "00030041003b0000000042004900000000430058000000670000000001010278"
        "00010000004900000041000101027900020000005800000042000101027a0003"
        "0000006700000000000000"
    )
    root = parse_config_bin(chain)
    assert root.name == "", root.name
    assert root.properties == {}
    assert [c.name for c in root.children] == ["CfgA"]
    cfga = root.children[0]
    assert [c.name for c in cfga.children] == ["A", "B", "C"]
    assert cfga.children[0].properties == {"x": 1}
    assert cfga.children[1].properties == {"y": 2}
    assert cfga.children[2].properties == {"z": 3}

    # class_with_array: class A has arr[] = {1, 2, 3};.
    with_array = _real(
        "0072615000000000080000006500000000010043666741002000000065000000"
        "0002004100340000000042005700000065000000000201027800010000000261"
        "7272000302010000000202000000020300000057000000000101027900020000"
        "006500000000000000"
    )
    root = parse_config_bin(with_array)
    a = root.children[0].children[0]
    assert a.properties == {"x": 1, "arr": [1, 2, 3]}, a.properties

    # class_plus_prop: scalar property alongside child classes.
    plus_prop = _real(
        "0072615000000000080000005c0000000001004366674100200000005c000000"
        "0003004100400000000042004e000000010276616c756500050000005c000000"
        "000101027800010000004e000000000101027900020000005c00000000000000"
    )
    root = parse_config_bin(plus_prop)
    cfga = root.children[0]
    assert [c.name for c in cfga.children] == ["A", "B"]
    assert cfga.properties == {"value": 5}, cfga.properties

    # append_i64_flags_first: voices[] += {"Male01"}; speed=10000000000;.
    append = _real(
        "0072615000000000080000003b00000000020501000000766f69636573000100"
        "4d616c65303100010673706565640000e40b54020000003b00000000000000"
    )
    root = parse_config_bin(append)
    assert root.properties == {"voices": ["Male01"], "speed": 10000000000}, root.properties

    # broken_enum_offset: enum offset points past EOF (fallback layout), and the
    # file has no enum table; the root still parses.
    broken = _real(
        "00726150000000000800000022cf00000001010273706563756c6172506f776572"
        "000000000000000000"
    )
    root = parse_config_bin(broken)
    assert root.properties == {"specularPower": 0}, root.properties

    # Reject non-rap data.
    for bad in (b"", b"not rapified", b"\x00raP" + b"\x00" * 8):
        try:
            parse_config_bin(bad)
        except (ValueError, TypeError):
            pass
        else:
            raise AssertionError(f"expected failure for {bad!r}")

    # ---------------------------------------------------------------------
    # Part 2: rapify() round-trips. Also exercise delete/extern skipping and
    # unknown-entry tolerance with hand-built raw streams.
    # ---------------------------------------------------------------------

    def _prop_entry(name: str, val) -> bytes:
        subtype, payload = _encode_scalar(val)
        return b"\x01" + bytes([subtype]) + _encode_cstring(name) + payload

    # delete / extern skipping + an unknown entry code must not crash.
    del_body = (
        b"\x00" + _encode_compressed_int(3)
        + b"\x04" + _encode_cstring("OldClass")    # delete OldClass;
        + b"\x03" + _encode_cstring("ForwardDecl")  # class ForwardDecl;
        + _prop_entry("value", 7)
    )
    del_data = (
        MAGIC + struct.pack("<I", 0) + struct.pack("<I", 8)
        + struct.pack("<I", 16 + len(del_body)) + del_body + struct.pack("<I", 0)
    )
    root = parse_config_bin(del_data)
    assert root.properties == {"value": 7}, root.properties
    assert root.children == []

    # Unknown entry code (0x99) stops the class body conservatively.
    unk_body = (
        b"\x00" + _encode_compressed_int(2)
        + _prop_entry("good", 1)
        + b"\x99" + _encode_cstring("garbage")     # unknown -> abort body
    )
    unk_data = (
        MAGIC + struct.pack("<I", 0) + struct.pack("<I", 8)
        + struct.pack("<I", 16 + len(unk_body)) + unk_body + struct.pack("<I", 0)
    )
    root = parse_config_bin(unk_data)
    assert root.properties == {"good": 1}, root.properties  # parsed before the unknown token

    # Round-trip a mixed tree (scalars, int64, arrays, nesting).
    src = ConfigClass(
        name="",
        children=[
            ConfigClass(
                name="CfgSomething",
                properties={"author": "me", "version": 1.5, "big": 5000000000},
                children=[
                    ConfigClass(
                        name="Item",
                        properties={"values": [1, 2, 3], "nested": [["a", "b"], 9]},
                    )
                ],
            )
        ],
    )
    rt = parse_config_bin(rapify(src))
    assert rt.children[0].name == "CfgSomething"
    assert rt.children[0].properties == {"author": "me", "version": 1.5, "big": 5000000000}
    item = rt.children[0].children[0]
    assert item.name == "Item"
    assert item.properties["values"] == [1, 2, 3]
    assert item.properties["nested"] == [["a", "b"], 9]

    # End-to-end: serialize a CfgFunctions config, parse it, extract names.
    cfg = ConfigClass(
        name="",
        children=[
            ConfigClass(
                name="CfgFunctions",
                children=[
                    ConfigClass(
                        name="ace_medical",
                        children=[
                            ConfigClass(name="medical", children=[
                                ConfigClass(name="setUnconscious", properties={"file": "a.sqf"}),
                                ConfigClass(name="setDamage", properties={"file": "b.sqf"}),
                            ]),
                        ],
                    ),
                    ConfigClass(
                        name="CBA_settings",
                        children=[
                            ConfigClass(name="init", properties={"preInit": 1}),
                        ],
                    ),
                ],
            )
        ],
    )
    from .cfgfunctions import extract_cfg_functions
    parsed = parse_config_bin(rapify(cfg))
    assert extract_cfg_functions(parsed) == {
        "ace_medical_fnc_setunconscious",
        "ace_medical_fnc_setdamage",
        "cba_settings_fnc_init",
    }

    print("rapified self-test passed")
